### ISSUE TITLE
Error integration SWAG 

### ISSUE THREAD

**Issue by zichichi** [openappsec/attachment#16]
I followed the following guide:
https://www.openappsec.io/post/how-to-deploy-open-appsec-on-a-docker-swag-linux-server

I used a virtual machine to compile the libraries, if I try to activate swag the system gives me this error:

`nginx: [emerg] dlopen() "/usr/lib/nginx/modules/ngx_cp_attachment_module.so" failed (Error relocating /usr/lib/libosrc_nginx_attachment_util.so: __libc_single_threaded: symbol not found) in /etc/nginx/nginx.conf:1`

**Comment by orianelou** [comment]
Hi @nekromantik,

We are excited to introduce the integration of open-appsec WAF with Docker SWAG! You can find full information in our docs and blog
https://www.openappsec.io/post/announcing-open-appsec-waf-integration-with-docker-swag-secure-web-application-gateway
https://docs.openappsec.io/integrations/docker-swag

We'll be happy if you could test it out and let us know what you think!

**Comment by zichichi** [comment]
I installed Docker Compose according to your instructions, but I keep getting this error:

docker "swag-attachmet" logs:

`nginx: [emerg] module "/usr/lib/nginx/modules/ngx_cp_attachment_module.so" is not binary compatible in /etc/nginx/nginx.conf:1`

**Comment by orianelou** [comment]
Hi, we're on it! Thank you for reporting this!

**Comment by orianelou** [comment]
Hi @zichichi, 

A fix has been deployed, please make sure to pull the latest image to get the version with the fix. 

Thank you for involvement!
