### ISSUE TITLE
Could anyone update nginx-proxy-manager-attachment  docker image ?

### ISSUE THREAD

**Issue by juanmafont** [openappsec/attachment#18]
This image has been update 13 days ago, but one of his packages (nginx-proxy-manager) has been update 5 days ago. The new version of nginx-proxy-manager (2.11.2) fix an error with the "map directive" -> see https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3474#issuecomment-2090366370

   So will be good that nginx-proxy-manager-attachment will include this.
   
   Thank you very much.

**Comment by orianelou** [comment]
Hi, We'll update in the NGINX Proxy Manager repo on every new release.
