### ISSUE TITLE
How Install on Ubuntu 24.04(Noble)

### ISSUE THREAD

**Issue by moonSandra** [openappsec/attachment#22]
I am a newbie.
I have an Nginx server.
I have followed the instructions, and everything is OK (CMake Done).
How do I know it is installed? How can I monitor it?
I don't understand anything.
How do I know if it is OK with Nginx?

**Comment by orianelou** [comment]
Hi, 

You can use the command open-appsec-ctl -s to get the status of the system. 

Also, from now on ubuntu 24 should be supported out of the box, so you could use our installer and won't have to compile yourself.
