### ISSUE TITLE
nginx, sleep, shared memory and retries

### ISSUE THREAD

**Issue by acpeakhour** [openappsec/attachment#7]
What is the longer term plan for error handling in the nginx module? Is there another method for submitting data to the service such as using a unix socket?

I can see for example hard coded retries with a hard coded sleep() being used between retries in ngx_http_cp_hold_verdict
and retries waiting with usleep waiting for a verdict in ngx_http_cp_receive_data_from_service.

How would you suggest monitoring the service?

**Comment by roybarda** [comment]
Not sure what you mean by error handling in nginx module... we have a fail open/close mechanism that can be configured between attachment and agent and it works in a way that every operation that requires use of this mechanism is operated in a different thread. 

When it comes to monitoring - I would suggest monitoring 5XX nginx return code. Any nginx error will be reflected using this code.

Unix sockets are not on our short term roadmap. We do consider other ways to connect to nginx.
